# traducoes.py
# ===== TRADUÇÕES PORTUGUÊS/INGLÊS =====

TRADUCOES = {
    'pt': {
        'titulo': '🌿 NutriVision',
        'subtitulo': 'Plataforma Inteligente de Deteção Precoce da Anemia, Fome Oculta e Insegurança Alimentar<br><br>para a Prevenção através de Intervenções Integradas nos Sistemas de Saúde e Agroalimentares',
        'login': 'Login',
        'usuario': 'Usuário',
        'senha': 'Senha',
        'entrar': 'Entrar',
        'credenciais': 'Credenciais de Teste',
        'perfil': 'Perfil',
        'usuario_senha': 'Usuário / Senha',
        'bem_vindo': 'Bem-vindo',
        'perfil_label': 'Perfil',
        'sair': 'Sair',
        'inicio': 'Início',
        'dashboard': 'Dashboard',
        'triagem': 'Triagem',
        'consultas': 'Consultas',
        'avaliacoes': 'Avaliações',
        'producao': 'Produção',
        'configuracoes': 'Configurações',
        'informacoes': 'Informações',
        'versao': 'Versão',
        'data': 'Data',
        'idioma': 'Idioma',
        'portugues': 'Português',
        'ingles': 'English',
        'preencha_campos': 'Preencha todos os campos!',
        'login_sucesso': 'Login realizado com sucesso!',
        'login_erro': 'Usuário ou senha inválidos!',
        'conectado_sucesso': 'Conectado com sucesso ao sistema!',
        'use_menu': 'Use o menu lateral para acessar as funcionalidades do seu perfil.'
    },
    'en': {
        'titulo': '🌿 NutriVision',
        'subtitulo': 'Intelligent Platform for Early Detection of Anemia, Hidden Hunger and Food Insecurity<br><br>for Prevention through Integrated Interventions in Health and Agri-Food Systems',
        'login': 'Login',
        'usuario': 'Username',
        'senha': 'Password',
        'entrar': 'Login',
        'credenciais': 'Test Credentials',
        'perfil': 'Profile',
        'usuario_senha': 'Username / Password',
        'bem_vindo': 'Welcome',
        'perfil_label': 'Profile',
        'sair': 'Logout',
        'inicio': 'Home',
        'dashboard': 'Dashboard',
        'triagem': 'Screening',
        'consultas': 'Consultations',
        'avaliacoes': 'Assessments',
        'producao': 'Production',
        'configuracoes': 'Settings',
        'informacoes': 'Information',
        'versao': 'Version',
        'data': 'Date',
        'idioma': 'Language',
        'portugues': 'Portuguese',
        'ingles': 'English',
        'preencha_campos': 'Please fill in all fields!',
        'login_sucesso': 'Login successful!',
        'login_erro': 'Invalid username or password!',
        'conectado_sucesso': 'Connected successfully to the system!',
        'use_menu': 'Use the sidebar menu to access your profile features.'
    }
}